version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres_matmassig
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: matmassig
    ports:
      - "5432:5432"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"  # Port pour la communication RabbitMQ
      - "15672:15672" # Port pour l'interface de gestion
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    networks:
      - app-network

  orchestrator:
    build:
      context: ./Matmassig/orchestrator
      dockerfile: Dockerfile
    container_name: orchestrator
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_matmassig:5432/matmassig
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "8080:8080" # Port exposé pour le service orchestrator
    restart: always
    networks:
      - app-network

  websocket-service:
    build:
      context: ./Matmassig/web-socket
      dockerfile: Dockerfile
    container_name: websocket-service
    ports:
      - "8089:8089" # Port exposé pour le WebSocket
    depends_on:
      - rabbitmq
    networks:
      - app-network

  recipe-service:
    build:
      context: ./Matmassig/recipe-service
      dockerfile: Dockerfile
    container_name: recipe-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_matmassig:5432/matmassig
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "8081:8081" # Port exposé pour le service recipe-service
    restart: always
    networks:
      - app-network

  review-service:
    build:
      context: ./Matmassig/review-service
      dockerfile: Dockerfile
    container_name: review-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_matmassig:5432/matmassig
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "8082:8082" # Port exposé pour le service review-service
    restart: always
    networks:
      - app-network

  inventory-service:
    build:
      context: ./Matmassig/inventory-service
      dockerfile: Dockerfile
    container_name: inventory-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_matmassig:5432/matmassig
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "8085:8085" # Port exposé pour le service inventory-service
    restart: always
    networks:
      - app-network

  authentification-service:
    build:
      context: ./Matmassig/authentication-service
      dockerfile: Dockerfile
    container_name: authentification-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_matmassig:5432/matmassig
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "8083:8083" # Port exposé pour le service authentification-service
    restart: always
    networks:
      - app-network

  notification-service:
    build:
      context: ./Matmassig/notification-service
      dockerfile: Dockerfile
    container_name: notification-service
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: admin
      SPRING_RABBITMQ_PASSWORD: admin
      WEBSOCKET_URL: ws://websocket-service:8089 # URL du serveur WebSocket
    depends_on:
      - rabbitmq
      - websocket-service
    ports:
      - "8084:8084" # Port exposé pour le service notification-service
    restart: always
    networks:
      - app-network
  recommandation-service:
    build:
      context: ./Matmassig/recommandation-service
      dockerfile: Dockerfile
    container_name: recommandation-service
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: admin
      SPRING_RABBITMQ_PASSWORD: admin
      WEBSOCKET_URL: ws://websocket-service:8089 # URL du serveur WebSocket
    depends_on:
      - rabbitmq
    ports:
      - "8086:8086" # Port exposé pour le service notification-service
    restart: always
    networks:
      - app-network

  userpreferences-service:
    build:
      context: ./Matmassig/userpreferences-service
      dockerfile: Dockerfile
    container_name: userpreferences-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_matmassig:5432/matmassig
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "8087:8087" # Port exposé pour le service review-service
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
